services:
  psql:
    image: postgres:alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
        ]
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  psql_volume:
    driver: local
  redis-data:
    driver: local
